#ifndef _VIGS_REGS_H_
#define _VIGS_REGS_H_

#define VIGS_REG_EXEC 0
#define VIGS_REG_INT 8
#define VIGS_REG_FENCE_LOWER 16
#define VIGS_REG_FENCE_UPPER 24

#define VIGS_REG_INT_VBLANK_ENABLE 1
#define VIGS_REG_INT_VBLANK_PENDING 2
#define VIGS_REG_INT_FENCE_ACK_PENDING 4

#endif
