obj-$(CONFIG_MARU_DUMMY) += maru_dummy.o
obj-$(CONFIG_MARU_SECURITY) += maru_dummy_security.o
obj-$(CONFIG_MARU_SDP_MEM) += maru_dummy_sdp_mem.o
obj-$(CONFIG_MARU_GPIO) += maru_dummy_gpio.o
obj-$(CONFIG_MARU_I2C_SDP) += maru_dummy_i2c_sdp.o
obj-$(CONFIG_MARU_MICOM_MSG) += maru_dummy_micom_msg.o
obj-$(CONFIG_MARU_MICOM_ISP) += maru_dummy_micom_isp.o