obj-$(CONFIG_MARU_VIRTIO_SENSOR) += maru_virtio_sensor.o	\
									maru_accel.o			\
									maru_geo.o				\
									maru_gyro.o				\
									maru_light.o			\
									maru_proxi.o			\
									maru_rotation_vector.o	\
									maru_haptic.o
