obj-$(CONFIG_MARU_VIRTIO_TOUCHSCREEN) += maru_virtio_touchscreen.o
obj-$(CONFIG_MARU_BACKLIGHT) += maru_bl.o
obj-$(CONFIG_MARU_VIRTIO_HWKEY) += maru_virtio_hwkey.o
obj-$(CONFIG_MARU_VIRTIO_KEYBOARD) += maru_virtio_keyboard.o
obj-$(CONFIG_MARU_VIRTIO_NFC) += maru_virtio_nfc.o
obj-$(CONFIG_MARU_VIRTIO_EVDI) += maru_virtio_evdi.o
obj-$(CONFIG_MARU_VIRTIO_SENSOR) += maru_virtio_sensor.o
obj-$(CONFIG_MARU_BRILLCODEC) += maru_brillcodec.o
