obj-$(CONFIG_MARU_VIRTIO_TOUCHSCREEN) += maru_virtio_touchscreen.o
obj-$(CONFIG_MARU_VIRTIO_HWKEY) += maru_virtio_hwkey.o
obj-$(CONFIG_MARU_VIRTIO_KEYBOARD) += maru_virtio_keyboard.o
obj-$(CONFIG_MARU_BRILLCODEC) += maru_brillcodec.o
obj-$(CONFIG_MARU_CAMERA) += maru_camera.o
obj-$(CONFIG_MARU_BACKLIGHT) += maru_bl.o
obj-$(CONFIG_MARU_OVERLAY) += maru_overlay.o
